### ISSUE TITLE
incorrect link

### ISSUE THREAD

**Issue by yusufades** [tgdwyer/tgdwyer.github.io#12]
is this link incorrect? where is it supposed to take you
the one called higher order functions at the top of the functional javascript page

https://github.com/tgdwyer/tgdwyer.github.io/blob/master/_chapters/functionaljavascript.md#L19

**Comment by tgdwyer** [comment]
fixed - it now takes you to the section on higher-order functions.

**Comment by yusufades** [comment]
now it takes me to a 404 error. im not sure where the section on higher order functions is
