### ISSUE TITLE
Add "hacktoberfest" topic

### ISSUE THREAD

**Issue by mariuszskon** [tgdwyer/tgdwyer.github.io#34]
[Hacktoberfest](https://hacktoberfest.digitalocean.com/) is an event which celebrates open source contributions. By adding the "hacktoberfest" topic/tag to this repository (as explained in more detail [here](https://hacktoberfest.digitalocean.com/details#maintainers)) means that contributors are incentivised to open pull requests, due to potentially being eligible for a free t-shirt or planted tree sponsored by DigitalOcean.
This can push beginners to contribute, and get more experienced folks a reason to not put off contributions.

Full disclosure: I'm interested in a free t-shirt :smile:

**Comment by tgdwyer** [comment]
Good idea.  Done
